#!/usr/bin/env python
# -*- coding: utf-8 -*-
# @Date    : 2020/1/4
# @Author  : Lin lin

---
url: http://api.help.bj.cn/apis/weather/

# log_conf
log:
  file_level: INFO
  console_level: DEBUG
  backup: 10
  file_name: default.log
  pattern: '[%(levelname)s][%(process)d][%(thread)d]--%(asctime)s--[%(filename)s %(funcName)s %(lineno)d]: %(message)s'